repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        types: [file]
        files: \.(py|js|html|json|yaml|yml|css|md)$
      - id: end-of-file-fixer
        types: [file]
        files: \.(py|js|html|json|yaml|yml|css|md)$
      - id: check-yaml
      - id: check-json
        files: \.json$
      - id: check-added-large-files
      - id: check-merge-conflict
